version: "3"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 100:100
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - exam
      - exam1

  exam:
    build: ./exam
    restart: unless-stopped

  exam1:
    build: ./exam1
    restart: unless-stopped

  
